remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: 'Afif Amir: Data Science Portfolio
description: A page to compile and showcase Afif's projects with regards to Data Science domain
